# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'XXBLibDemo' do
    pod 'XXBLibs',:path => "../"
    pod 'XXBLibs/Category',:path => "../"
    pod 'XXBLibs/Others',:path => "../"
end

target 'XXBLibDemoTests' do
    pod 'XXBLibs',:path => "../"
end

